### ISSUE TITLE
Cant install! Blank page

### ISSUE THREAD

**Issue by Gibbz** [tbar0970/jethro-pmm#111]
Ive done a previous install without any issues. 
Im trying to transfer over to a new server, and keep getting stuck.

I have installed mysql, php, setup the user, setup apache, and tried installing pear... I had issue with pear, so put the dropin file in instead. 
Now im just getting a blank page!

So i have /www/jethro/ with the jethro files
Ive extracted the zip, and that ends up /www/jethro/MDB2_Dropin/ (which contains folder and MDB2.php)

Php has no problem accessing the database, the config file is all setup and seems to work (I changed the baseURL and that redirects, so something is working).

Any ideas what I missed?

Edit: Just noticed the blank page shows the jethro icon, so scratching my head on why this is blank!

**Comment by Gibbz** [comment]
Ok ive reinstalled pear, and thats helped get it working..
You guys need to update your readme, as the drop in zip does not work.

I enabled error reporting and get a whole bunch of errors:




Strict Standards: Non-static method MDB2::factory() should not be called statically in /home/gatewayadmin/www/jethro/include/init.php on line 56

Strict Standards: Non-static method MDB2::parseDSN() should not be called statically in /usr/share/php/MDB2.php on line 376

Strict Standards: Non-static method MDB2::loadClass() should not be called statically in /usr/share/php/MDB2.php on line 385

Strict Standards: Non-static method MDB2::classExists() should not be called statically in /usr/share/php/MDB2.php on line 327

Strict Standards: Non-static method PEAR::isError() should not be called statically in /usr/share/php/MDB2.php on line 386

Deprecated: Non-static method MDB2::parseDSN() should not be called statically, assuming $this from incompatible context in /usr/share/php/MDB2.php on line 2298

Strict Standards: Non-static method MDB2::setOptions() should not be called statically in /usr/share/php/MDB2.php on line 392

Strict Standards: Non-static method PEAR::isError() should not be called statically in /usr/share/php/MDB2.php on line 393

Strict Standards: Non-static method MDB2::isError() should not be called statically in /home/gatewayadmin/www/jethro/include/init.php on line 57

Strict Standards: Non-static method MDB2::isError() should not be called statically in /home/gatewayadmin/www/jethro/include/init.php on line 57
prodb shiz
Deprecated: Non-static method MDB2::classExists() should not be called statically, assuming $this from incompatible context in /usr/share/php/MDB2.php on line 2567

Deprecated: Non-static method MDB2::isResultCommon() should not be called statically, assuming $this from incompatible context in /usr/share/php/MDB2.php on line 2573

Deprecated: Non-static method PEAR::isError() should not be called statically, assuming $this from incompatible context in /home/gatewayadmin/www/jethro/include/user_system.class.php on line 60

**Comment by tbar0970** [comment]
Hi Gibbz

All those errors are E_DEPRECATED or E_STRICT warnings.  They don't stop anything from working.  I've got a note to do some work on resolving them when there's time, but in the meantime the solution is to set the error reporting level to ignore them (which Jethro does).  (This is the case for lots of php software that is a few years old).  As you can see, many of them come from the MDB2 library rather than Jethro itself, and I'm hoping to stop using that library in due course, in favour of the newer PHP PDO.

Did you figure out what the problem with the MDB2 problem drop in was?  It's been working fine for years but I wonder if there's an incompatibility with the most recent versions of PHP.  Many servers are still using older versions which are still supported by the OS vendors.

When  you're getting a blank screen, checking the server's php error log and httpd error log is a good place to look.

**Comment by Gibbz** [comment]
I'm not sure, reinstall via apt-get worked.
I suspect it was due to being an old version incompatibility....
Ive disabled the debug and is working well! 
Thanks :)
