### ISSUE TITLE
upgrade problem

### ISSUE THREAD

**Issue by colin-watts** [tbar0970/jethro-pmm#17]
Hi. Just upgraded from 2.7.1 to 2.9.4
(Had the same problems backing up DB that Neil Atwood had but have got through those ok now)
Ran the SQL upgrades for 2.8 & 2.9 and edited the new conf.php

However, when try to run I get an error message: "Fatal error: Could not generate random string in /home/kensingt/public_html/jethro/jethro-pmm/include/general.php on line 617"

Any ideas?

Thanks
Colin Watts

PS: I also need to use the MDB2 package if that is relevant

**Comment by colin-watts** [comment]
I have patched in the 'USE_POOR_RANDOMS' code that I found on github (include/general.php) and that has overcome the problem for now, but a proper solution would be preferable ....
Thanks
Colin Watts

**Comment by tbar0970** [comment]
Hi Colin
Glad you found that code!  That is the workaround I was going to suggest.  It's coming out in the next release (you'll need to add define('USE_POOR_RANDOMS', 1); to your conf.php)
Basically the problem is that your web server doesn't provide a good way of generating a random number, and good random numbers are a key part of encrypting passwords etc.
This came up recently for another Sydney Anglican church who were using some web hosting that I suspect, for this reason, is not being well maintained.  They decided it was time to move to Easy Jethro.

**Comment by colin-watts** [comment]
Thanks, Tom

I'll stick with this workaround.
Yes, we are still using the Sydney Anglican SDS hosting package for Jethro.

After a bit more debugging I discovered that "openssl_random_pseudo_bytes" does not exist on the system (despite being PHP 5.4.29) and so is bypassed and "fopen('/dev/urandom','rb')" fails as well (despite being a linux system).  So not much else to try!!

Colin

**Comment by colin-watts** [comment]
Thanks, Tom for your help.

While trying not to be over-pedantic, I have two suggestions (especially given that this code is not yet released):

1) should not the "if" statement (on line #586) include "&& USE_POOR_RANDOMS" - otherwise define('USE_POOR_RANDOMS', FALSE) will not give the desired effect

2) would it be better instead to ditch the 'USE_POOR_RANDOMS' setting altogether and just use your new code to replace the 'trigger_error' statements.  This would automatically yield the most secure result attainable on the user's system without adding another conf.php entry.  (It may also prevent anyone bothering you any further about this!)

ie:
	if (strlen($pr_bits) < $chars) {
		$options = array_merge(range('a', 'b'), range('A', 'Z'), range(0, 9));
		$res = '';
		for ($i=0; $i < $chars; $i++) {
			$res .= $options[rand(0, count($options)-1)];
		}
		return $res;
	}

Colin

(Sorry, wasn't sure where else to propose this suggestion)

**Comment by tbar0970** [comment]
Hi Colin, thanks for the input.  Because the rand() function doesn't produce good quality random numbers, I don't want Jethro to use it unless the system administrator has explicitly said to.  It's basically settling for a lower level of security and I don't want that to be part of the default Jethro behaviour.

**Comment by colin-watts** [comment]
I take your point.
Impressed by your work and support.

PS:  point (1) is still valid is it not?
ie line #586 would best be:
	if (defined('USE_POOR_RANDOMS') && USE_POOR_RANDOMS) {
Colin

**Comment by tbar0970** [comment]
Yes, that would be needed for it to be defined as false.  But it's designed to be either true or not defined.

**Comment by colin-watts** [comment]
At least encountering this problem has lead me to some interesting articles on random number generation!  Thanks again for your help.
