### ISSUE TITLE
Sms Box not displayed correctly

### ISSUE THREAD

**Issue by mikaoelitiana** [tbar0970/jethro-pmm#205]
I am using a custom theme colors and my sms bow is not displayed correctly: it has no background and it makes the content difficult to read: 

<img width="359" alt="capture d ecran 2016-06-22 a 10 44 49" src="https://cloud.githubusercontent.com/assets/674667/16258552/12cae2ea-3867-11e6-883b-69c9a4992fd5.png">

**Comment by vanoudt** [comment]
Hmmmm - that does look odd. I'm using custom theme colours too, but the sms box works fine for me. Having said that, I've done a bit of tidying of the code behind the SMS box display in my reworking of the SMS sending code (issue 139)

**Comment by vanoudt** [comment]
From memory, it's because the SMS box was being placed in the wrong spot. I've got code that shifts it around to being in a different spot, so that actually goes on top. (But it has been a while since I've looked at it)

**Comment by mikaoelitiana** [comment]
@vanoudt so you PR should fix this then? I hope it would be accepted soon

**Comment by vanoudt** [comment]
It should do - since I don't have the issues you're describing, and am also using custom theme colours...

**Comment by tbar0970** [comment]
@mikaoelitiana what are you clicking to get the SMS box to appear?  (Which page are you on?)

**Comment by mikaoelitiana** [comment]
This is on the View Roster page, when I want to send SMS notification to all people. 

![juin-30-2016 07-47-44](https://cloud.githubusercontent.com/assets/674667/16477051/feac6b04-3e96-11e6-9126-538bcbe3b087.gif)

**Comment by tbar0970** [comment]
Thanks for that.  Nifty animation!

**Comment by tbar0970** [comment]
I've fixed the presenting layout problem.  But @vanoudt it would be good to include this in your AJAX-SMS work.  

I'm thinking it would be nice if the page HTML just had
`<span class="clickable" data-send-sms="0417333444,0418222333,0419777888">SMS All</span>`

and the JS could find all elements with this data-send-sms attribute, attach an onclick handler, so that when they are clicked a send-sms modal is built from scratch, which would then submit via ajax.   Much cleaner than having individual send-sms forms all over the place like we now do.

This would be a universal solution for rosters, reports and individual persons.

**Comment by vanoudt** [comment]
I'll have a look at that sometime in the next few days
