### ISSUE TITLE
SMS sending fails when current user has blank mobile number

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#344]
Often an SMS gateway is configured so that the SenderID is set to the current Jethro user's mobile number.  If their mobile number is blank this means a blank SenderID is used, which triggers errors.

Think about how to spot this.

The tricky thing is that sometimes the SMS gateway is configured to send from some fixed SenderID so the lack of mobile number is not a problem.

But requiring someone to have their mobile number entered is not a big deal so we could probably just require it for all SMS sending anyway.

**Comment by tbar0970** [comment]
+1

**Comment by vanoudt** [comment]
Maybe we can tack this onto the permission system... if there's no mobile number associated with a user, assume that they don't have the PERM_SENDSMS permission.

We could maybe add another configuration option - something like "SMS_FROM_NUMBER" that, if configured, is used instead of the current person's mobile number...

**Comment by vanoudt** [comment]
Just submitted a pull request that fixes this: #483
