### ISSUE TITLE
SMS message input box allows rich text which can cause problems

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#400]
Hey @vanoudt 

Do you remember why the input box for SMS messages got changed from a textarea to a div with contenteditable=true ?  I can't find the PR that it came from (I did some manual merging at the time)

I think it is causing some problems for users who paste URLs in there - they end up as rich text which then confuses the character counter and/or chokes things further down the line...

https://github.com/tbar0970/jethro-pmm/blob/3d9449fd117fff88e45ce715d28c01478a619677/include/sms_sender.class.php#L194

**Comment by vanoudt** [comment]
Hmmm.... I recall that there was a reason. I think it was in order to get
it out of the context of the form, though I'm not sure. I'll have a look
this weekend.

Some js should fix that....
https://stackoverflow.com/questions/24408028/html5-contenteditable-div-accept-only-plaintext.
Suggests something like:

function convertToPlaintext() {
  var textContent = this.textContent;
  this.innerHTML = "";
  this.textContent = textContent;
}

var contentEditableNodes = document.querySelectorAll('[contenteditable]');

[].forEach.call(contentEditableNodes, function(div) {
  div.addEventListener("input", convertToPlaintext, false);
});

**Comment by tbar0970** [comment]
Thanks for that.  Yes, we could fix it with JS, but if there's a way to get the basic textbox to work for us that would be simpler.  If we're constructing the AJAX request in our own JS then changing div.innerHTML to textbox.value shouldn't be hard... but maybe there's more to it.

**Comment by vanoudt** [comment]
Hmmm... Let me do some experimentation and get backto you!

**Comment by vanoudt** [comment]
Got an idea on fixing this, and the text  encoding issue at the same
time.... Will put in a pull request in the next week or so...

**Comment by vanoudt** [comment]
I still can't remember why I changed it to the div - still think it might be the "forms within forms" issue, not sure why....

But PR #411 fixes this problem....
