### ISSUE TITLE
Bug report: Batch email problem

### ISSUE THREAD

**Issue by AlwynBarry** [tbar0970/jethro-pmm#54]
From a report the Batch Email feature emailed the same people in each batch, and the full set (59 people) were emailed each time.  Not sure why ... it worked previously but I've not used this feature since the 2.10 update and I'm now running 2.10.4, and so I guess the problem could have been introduced anywhere in the 2.10 series!  Sorry to not be of more help!

**Comment by GatesheadBen** [comment]
I can confirm this issue.
It looks like line 134 of call_email.class.php has ...getHref($emails...
rather than ...getHref($chunk...

<a class="btn" href="<?php echo $this->getHref($emails, $public); ?>"
onclick="this.style.textDecoration='line-through'" <?php echo
email_link_extras(); ?>>Email Batch #<?php echo ($i+1); ?></a>&nbsp;&nbsp;
<a class="btn" href="<?php echo $this->getHref($chunk, $public); ?>"
onclick="this.style.textDecoration='line-through'" <?php echo
email_link_extras(); ?>>Email Batch #<?php echo ($i+1); ?></a>&nbsp;&nbsp;



On 9 June 2015 at 15:18, AlwynBarry <notifications@github.com> wrote:

> From a report the Batch Email feature emailed the same people in each
> batch, and the full set (59 people) were emailed each time. Not sure why
> ... it worked previously but I've not used this feature since the 2.10
> update and I'm now running 2.10.4, and so I guess the problem could have
> been introduced anywhere in the 2.10 series! Sorry to not be of more help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbar0970/jethro-pmm/issues/54>.
>



-- 
07858 739412
11 Jubilee Ave - NE9 7HN
