### ISSUE TITLE
setting in 'system configuration' to limit the number of sms messages sent at one time?

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#650]
This is more of a question than an 'issue'. 

Is there a limit on how many sms messages can be sent at one time (I can't see one in sms_sender.class.php)?  

I have a diy 'sms gateway'. It works fine with a smallish number of recipients - but had a few fails with a larger group. I want to introduce a 'sleep' into the gateway script to slow the sending of texts but suspect this will cause Jethro to time-out?

I expect sending bulk sms messages will 'time out' after 30s (or whatever the default php time-out is set in php.ini?). So if the gateway takes too long sending the txt message to the array of recipients ... then I expect Jethro will report an error? (and the process of sending to recipients may stop part-way through). BUT I can't see any 'issues' being raised by other users, so I think feel I must be missing something.

thanks

**Comment by tbar0970** [comment]
Yes, the normal php/apache/browser timeout will apply.  And I suspect there is a timeout built into the http-client that Jethro uses to connect to eh gateway.  Commercial gateways receive the job in one go, and then go out and send all the messages as a separate process.  Jethro kinda relies on this behaviour since it doesn't have any background-sending built in.

**Comment by s4069b** [comment]
thanks for the clarification. I guess commercial gateways must return a confirmation for each recipient prior to actually sending the text message.

**Comment by s4069b** [comment]
In my case I think I'll return a positive confirmation immediately but then have the gateway email the user with a list of what actually happened (send / fail for each recipient).

**Comment by tbar0970** [comment]
Fair enough. I think the commercial gateways return a semi-immediate "yes that looks fine, we can send that" message (which is what Jethro looks at), and then later you can look up the final status of the message delivery (which Jethro doesn't do).

**Comment by vanoudt** [comment]
I'm in the process - very intermittently - of rewriting the SMS code to
more fully support different SMS providers. (Our new provider doesn't work
with the current code, so I've hacked in a fix in our site for now). The
plan will be to enable connecting this to the "Communications" tab that
I've sent a PR in for, so that replies will be included in the Jethro
system too.

When an sms provider with quirks - like this one - are found, a new
"Provider" class can be made. This could hand off sending messages in
batches using cron - or anything else like that.

Not a project I've got a lot of time for - but I work on it every now and
again. :-)

God bless,
Nick

**Comment by vanoudt** [comment]
I'd be interested to know what SMS gateway you're using - if you're free to
say. They all seem to have slightly different APIs and quirks!

God bless,
Nick

**Comment by s4069b** [comment]
Hi Nick,
I have a diy hack on a raspberry pi. Combination of php that interacts with jethro - saving the outgoing messages and then a bash script that sends the messages. It works well with bulk messages of a Sunday (with service / zoom links for example) but I've not tried it with roster reminders (yet)

**Comment by vanoudt** [comment]
Interesting! How do you send the messages from the pi?

**Comment by s4069b** [comment]
Using the Huawei HiLink API with a 4G Dongle (prepaid optus Huawei e3372 - apparently they are not locked). I googled and grabbed hilink.sh and then wrote my own bash to interact with it. I don't use the dongle for data, or calls - just sms.  Incoming texts forward to email with cron job.

**Comment by vanoudt** [comment]
What a great solution! So much nicer than having to use an external
provider. And probably a fair bit cheaper, too! When I get around to
finishing the SMS rewrite, it would be great to work that into an
SMSProvider class for Jethro, so that others can use it . If you'd be happy
to share code / write the provider down the track, that would be fantastic!

God bless,
Nick

**Comment by s4069b** [comment]
Happy to share my dodgy-hack coding. The setup is only good for simple texts (ie no images or attachments) but I guess external providers might be the same? Also, need to take care if you're going to open your pi up to the internet (I told my router to only accept incoming requests from one ip address (where our Jethro install is hosted). I think you could do that in php (limit to one ip) too?

**Comment by s4069b** [comment]
Someone smarter than me could probably have their pi pair with their phone and send texts using bluetooth.

**Comment by vanoudt** [comment]
That would ve wonderful! We could implement either an IP based check, or a
client key, which is what most providers use.

God bless,
Nick
