### ISSUE TITLE
Bulk SMS recorded as Note when even when 'Save as note' is unchecked 

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#664]
Using Jethro 2.28.1:

Jethro's SMS screen includes a 'Save as note' checkbox, which determines whether the outgoing SMS is also recorded as a note.

When a SMS is sent directly to an individual, the checkbox is honored: 

![image](https://user-images.githubusercontent.com/205995/90224866-b1829b80-de53-11ea-832b-2812b7265367.png)

However if a SMSes are sent in bulk from a search, as here: 

![image](https://user-images.githubusercontent.com/205995/90224474-1093e080-de53-11ea-8748-b768d8746a05.png)

Then regardless of 'Save as note' being unchecked, a note is created:

![image](https://user-images.githubusercontent.com/205995/90224520-230e1a00-de53-11ea-921b-3e6e3fa87621.png)

**Comment by tbar0970** [comment]
@jefft is this still happening? What browser?

**Comment by tbar0970** [comment]
I hit this today.
Sent a SMS to a batch of people
did NOT tick "save as note"
It sent OK
On the NEXT page load (doing something else), I got a bunch of errors that had been stored in the session:
![image](https://github.com/tbar0970/jethro-pmm/assets/2133676/bc8c870e-172e-4b96-aaac-9e649d4df631)

The errors were probably because of (a) this bug, and (b) 'default note subject' setting being blank
![image](https://github.com/tbar0970/jethro-pmm/assets/2133676/c372a849-dd99-451f-89fe-3a0106ff3318)

**Comment by tbar0970** [comment]
Can't replicate any more.  Did I bump the "save as note" checkbox in the case above??

**Comment by tbar0970** [comment]
Since I can't replicate and there are no further reports, I'm closing this. Can re-open if it recurs.

**Comment by tim-pearce** [comment]
I just sent a bunch of SMSes and didn't notice that the 'create note' button was pre-ticked.
I created a couple hundred unwanted notes. I ended up deleting them from the database usinf phpMyAdmin.

**Comment by tbar0970** [comment]
Thanks for the report. Really hard to work out where this one is coming from - even whether the problem begins before or after the "send sms" request is sent to the server.
