### ISSUE TITLE
It is not possible to add a person with a User who has access permission.

### ISSUE THREAD

**Issue by IsaiaSilva** [tbar0970/jethro-pmm#666]
A user is protected with access permission to ADD Person.
However, after logging in with the selected user, the option to ADD Person is not displayed.

For more information, check the images attached.

**Comment by tbar0970** [comment]
Thanks for the clear problem report. This is actually intended behaviour.  By default, users who are restricted to a congregation/group can't add new persons/families. This is because they can't see if the person/family already exists in a different congregation/group and so they could create duplicates without realising.

But you can change this using this setting in Admin > System Config:

![image](https://user-images.githubusercontent.com/2133676/91672197-51d50180-eb70-11ea-876c-c457e5c177e6.png)

Hope that helps :)

**Comment by tbar0970** [comment]
(I removed the images in the original post since they had somebody's name and photo in them)

**Comment by IsaiaSilva** [comment]
Thanks for the quick return. His information was quite illuminating.
Thank you for discovering an original photo.

May Christ Jesus bless us for such dedicated and wise people.
