### ISSUE TITLE
Option to select people who are NOT in a particular congregation (or do NOT have a particular field filled)

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#701]
It would be handy to be able to setup a report that returns people who are NOT in any congregation, or not in a particular congregation or do not have a particular field filled.... similar to the option to return people who are not in particular group. 

Where's this need come from? Our youth group leaders have restricted access to two congregations (so that we don't accidentally have them send emails to, say, someone from Kids Club). Just now one of them added someone to Jethro who they thought was not there - turns out they are in Jethro from Kids Club but someone didn't assign them to a Congregation.. .so they were not visible to the Youth Group leader. No we have two entries to sort out.

I went to setup a report to return anyone else who is not assigned to a congregation, and discovered I can't build a report like that. I'm sure there are other situation where NOT or NONE would be handy.

**Comment by tbar0970** [comment]
Fair feature request for reports.

Re the situation that generated it: There is a system-wide setting regarding whether restricted users can add new families/persons. It defaults to "no" because of the issue here - restricted users can't know if a person they're adding already exists beyond their field of vision. It sounds like you have that setting set to "yes" which you might want to reconsider.

**Comment by s4069b** [comment]
Thanks. I changed the system wide setting. I expect It'll cause some grief... let see.

**Comment by tbar0970** [comment]
You can now create a report "that have congregation = "(don't select any options) and it will show people with no congreation.
