### ISSUE TITLE
mailchimp_sync timeout error at lines 246 and 247

### ISSUE THREAD

**Issue by kristanslack** [tbar0970/jethro-pmm#765]
Hi,

I'm using a cron job to run the mailchimp_sync.php every Monday. For the past few weeks I receive two fatal error emails about it:

> Fatal error: [Syncing report 2 to list 41f1a38d0e] Batch 98ycf4ygmc has been running for more than 5 minutes. Giving up. in /home/aliceang/public_html/jethro/scripts/mailchimp_sync.php on line 247

> Fatal error: [Syncing report 2 to list 41f1a38d0e] Batch 4hcm4kxtcc has been running for more than 5 minutes. Giving up. in /home/kristano/public_html/jethro/scripts/mailchimp_sync.php on line 246

I can open a terminal from my domain hosting page, and run the php script manually without errors, so I'm not sure what's going on here.

**Comment by s4069b** [comment]
My guess is that when cron runs the job it's running as a different user with a different path. So if the script runs in terminal that's a good sign - it should run in cron too if you feed it the correct path to php. That's my thoughts. 
for example on on server I need to start a cron job with:
"/usr/local/cpanel/3rdparty/bin/php ..."
and on another 
"/usr/bin/php ... "
Hope that makes sense.

**Comment by tbar0970** [comment]
I don't think this kind of timeout would be caused by a cron user issue or php path issue. 
That particular error happens when Jethro has sent a bunch of operations to Mailchimp (add this subscriber ,delete that subscriber, etc) but Mailchimp takes more than 5 minutes to handle it. Normally 5 minutes should be plenty of time for it to complete.
It could be there are network issues causing the delay?
When you run it in the command line, how long does it take?
I would double check the relevant report and MC list to check it's not trying to sync a million records or whatever.
Something else you can try is to edit mailchimp_sync.php and on line 31 change it to `$DEBUG=1;` or `$DEBUG=2;` so it spits out more info about what it's doing.

**Comment by kristanslack** [comment]
It resolved. I did modify the cron job to use the longer path to php. I presume that was it - sorry I didn’t notify you - I was just relieved to no longer receive puzzling timeout emails every Monday :)
