### ISSUE TITLE
Hide 'Add a planned absence' from archived members

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#812]
When a person has their status changed to 'Archived', they can still access Jethro proper and the members section. This is slightly surprising to me, but anyway.

The problem is that if an archived user:
- logs into the members section
- goes to Rosters -> 'Add a planned absence', and submits the form

Jethro breaks with the generic 'An error occurred' message. If one fixes #811, a more useful error appears:
```
SYSTEM ERROR (ERROR)
Attempt to add absence for a person outside the users family

Show Details
Line 26 of File /srv/www/jethro/2.31.2/app/members/views/view_0_add_planned_absence.class.php
	Array
(
    [0] => Array
        (
            [file] => /srv/www/jethro/2.31.2/app/members/views/view_0_add_planned_absence.class.php
            [line] => 26
            [function] => trigger_error
            [args] => Array
                (
                    [0] => Attempt to add absence for a person outside the users family
                    [1] => 256
                )

        )

    [1] => Array
        (
            [file] => /srv/www/jethro/2.31.2/app/include/system_controller.class.php
            [line] => 128
            [function] => processView
            [class] => View__Add_Planned_Absence
            [type] => ->
            [args] => Array
                (
                )
```

If we plan to allowed archived users to access the members section:
1) Their archived status should be clearly visible somewhere
2) The 'Add a planned absence' link should be greyed out, with a rollover explaining the reason ('your account is archived').

**Comment by jefft** [comment]
Also, an archived member adding a planned absence triggers the following stacktrace:
```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`jethro`.`planned_absence`, CONSTRAINT `planned_absencecreator` FOREIGN KEY (`creator`) REFERENCES `staff_member` (`id`)) 
Line 240 of /home/jethro/code/2.31.2/include/db_object.class.php

USER:       73 
REFERER:    https://jethro/members/?view=_add_planned_absence
USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

REQUEST: 
Array
(
    [view] => _add_planned_absence
    [new_planned_absence_submitted] => 1
    [personid] => Array
        (
            [0] => 73
        )

    [start_date_d] => 8
    [start_date_m] => 8
    [start_date_y] => 2022
    [end_date_d] => 8
    [end_date_m] => 8
    [end_date_y] => 2022
    [comment] => 
)


BACKTRACE:
Array
(
    [0] => Array
        (
            [file] => /home/jethro/code/2.31.2/include/db_object.class.php
            [line] => 240
            [function] => query
            [class] => PDO
            [type] => ->
            [args] => Array
                (
                    [0] => INSERT INTO planned_absence (`personid`, `start_date`, `end_date`, `comment`, `creator`)
				 VALUES ('73', '2022-08-08', '2022-08-08', '', '73')
                )

        )

    [1] => Array
        (
            [file] => /home/jethro/code/2.31.2/include/db_object.class.php
            [line] => 207
            [function] => _createFinal
            [class] => db_object
            [type] => ->
            [args] => Array
                (
                )

        )

    [2] => Array
        (
            [file] => /home/jethro/code/2.31.2/members/views/view_0_add_planned_absence.class.php
            [line] => 41
            [function] => create
            [class] => db_object
            [type] => ->
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => /home/jethro/code/2.31.2/include/system_controller.class.php
            [line] => 126
            [function] => processView
            [class] => View__Add_Planned_Absence
            [type] => ->
            [args] => Array
                (
                )

        )

    [4] => Array
        (
            [file] => /home/jethro/code/2.31.2/members/index.php
            [line] => 58
            [function] => run
            [class] => System_Controller
            [type] => ->
            [args] => Array
                (
                )

        )

)

```

**Comment by tbar0970** [comment]
Thanks for the report.

Current behaviour is that archived persons can log in to the member area, but cannot see any persons other than themselves (see the definition of the `member` view in the DB).  I have a feeling this was done on the (legal-ish?) principle that people should always be able to edit personal data that an organisation holds about them, even if they're no longer doing business with the organisation.  Open to counter-arguments.

Archived persons can log into the control centre if they have an active account (it's possible for the person record to have status=archived but the user account to have status=active).  I think this was for simplicity - when you look at the list of active user accounts, it's an accurate picture of who has access, without other factors in the mix.  But it would be reasonable to add logic so that when a person is archived, their user account is also de-activated, with a note explaining it.  (Like when you archive the last remaining member of a family, the family record gets archived too).

In principle I can't see a problem with an archived person adding a planned absence.  Maybe they'll get de-archived tomorrow and it will be useful.  So if there's an easy way to fix the error above so it works, I'll solve it that way.

**Comment by jefft** [comment]
Yes, I like Jethro being non-discriminatory against archived people. I think it's just an overzealous assert-like logic check, that can be removed.
