### ISSUE TITLE
How to change the order in which group members appear in attendance marking list

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#938]
When marking attendance for a group, the members are ordered by status first, then last name/family name. 
How can I change this so that they appear in alphabetic order, not status order?
This is more of a question than an 'issue'

**Comment by jefft** [comment]
There used to be an 'attendance list order' setting, with default value 'status ASC, family_name ASC, familyid, age_bracket ASC, gender DESC'.

This setting was removed from the web interface, and relocated to the server-side configuration file in the last Jethro release (#869), because the implementation (a snippet of raw SQL) was a security risk, and also easy to mess up. You now need to set ATTENDANCE_LIST_ORDER in `conf.php`.

**Comment by s4069b** [comment]
Thanks Very helpful. I have fixed.
